FROM node:latest

# run commands inside this repository
WORKDIR /usr/src/app

# install chromium for headless browser tests
#ENV CHROME_BIN=/usr/bin/chromium-browser
#RUN apk add --no-cache chromium udev ttf-freefont

# Expose the port the app runs in
EXPOSE 3000
EXPOSE 35729
